### PR TITLE
ZUR-152 My PR removes all import leading to the src-old folder and also all unused refs #2603 

### PR DESCRIPTION
**Pull request by sulaimon23**

### CODE REVIEW

**Comment by sulaimon23** [comment]
@JulianaSau Done.
Thank you

**Review by JulianaSau — APPROVED** [review]

**Comment by JulianaSau** [comment]
Could you add the screenshots of that link component that you added @sulaimon23

**Comment by sulaimon23** [comment]
Screenshot 2022-11-11 at 4 14 44 PM
Screenshot 2022-11-11 at 4 15 52 PM
@JulianaSau  Done

**Comment by JulianaSau** [comment]
I checked the description of your ticket and it says clean up the privacy policy page.
You only removed links to the old-src folder. The UI of the page also needs some work.

**Comment by sulaimon23** [comment]
@JulianaSau  No UI was provided. But done now. Thanks

**Comment by JulianaSau** [comment]
Add an image showing the changes to the UI. Then always ensure your branch is up to date with the dev branch

**Comment by sulaimon23** [comment]
Screenshot 2022-11-12 at 11 46 42 PM (2)
Screenshot 2022-11-12 at 11 46 51 PM (2)
Screenshot 2022-11-12 at 11 46 59 PM (2)
@JulianaSau  Done also branch up to date

**Comment by sulaimon23** [comment]
@JulianaSau made the changes to this.

**Comment by sulaimon23** [comment]
Screenshot 2022-11-14 at 9 27 33 AM
Screenshot 2022-11-14 at 9 27 39 AM
Screenshot 2022-11-14 at 9 27 46 AM
Screenshot 2022-11-14 at 9 27 51 AM

@JulianaSau page has been revamped. Thanks

**Pull request merged**
