### PR TITLE
Fix the padding issue in the channel name

### PR DESCRIPTION
**Pull request by The-Legend-Developer**
# Fixes Issue
**My PR Fixes ID-94**

# Changes proposed

## What were you told to do ?
**Fix the padding issue in the channel name**
### Additional Task
**Fix the spacing issue in the channel name**

## What did you do ?
I removed the margin left property that moved the arrow too much from the [CSS file from the message room view header](https://github.com/zurichat/zc_main/blob/dev/packages/ui/src/message-room-view-header/message-room-view-header.module.css) and also updated the displayed output at [the message room view header](https://github.com/zurichat/zc_main/blob/dev/packages/ui/src/message-room-view-header/MessageRoomViewHeader.jsx) so as to give it some spacing
# Check List (Check all the applicable boxes)

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I am making a pull request against the **dev branch** (left side).
- [X] My commit messages styles matches our requested structure.
- [X] My code additions will fail neither code linting checks nor unit test.
- [X] I am only making changes to files I was requested to.

# Screenshots/ Videos
What the site looked like before 
Site before changes

After I added my changes
Site after changes

### CODE REVIEW

**Comment by The-Legend-Developer** [comment]
@JulianaSau This is the new pull request

**Review by JulianaSau — APPROVED** [review]

**Comment by JulianaSau** [comment]
Great work. You're actually the first person to follow this pr template well😂😂😂

**Comment by JulianaSau** [comment]
I'll merge now

**Comment by Michaelajayi150** [comment]
Oh wow... Thanks 😅

**Comment by The-Legend-Developer** [comment]
Oh wow... Thanks 😅
Stage 4 here I come 🔥

**Pull request merged**
