### PR TITLE
[ZUR-154] Move Plugin link to the footer & Fix Plugin Page

### PR DESCRIPTION
**Pull request by akuya-ekorot**
- improvement/frontend: move plugin link to footer and improve the plugins page

### CODE REVIEW

**Comment by akuya-ekorot** [comment]
close #2545

**Comment by akuya-ekorot** [comment]
## 1. Removed the plugin link as shown below.
remove plugin link

## 2. Moved the plugin link to the footer as shown below.
footer

## 3. Fixed the plugin page to showcase Music, Chess and DM plugins.
Fix Plugin Page 1
Fix Plugin Page 2

**Comment by JulianaSau** [comment]
Looks good @akuya-ekorot

**Comment by JulianaSau** [comment]
@akuya-ekorot pull recent changes, resolve conflicts then tag me when you're done

**Comment by akuya-ekorot** [comment]
@JulianaSau I've resolved the conflict.

**Comment by JulianaSau** [comment]
Pull again @akuya-ekorot

**Comment by akuya-ekorot** [comment]
Done. Pulled and resolved conflicts. @JulianaSau

**Comment by JulianaSau** [comment]
Okay

**Pull request merged**
