### PR TITLE
ZUR-153 My PR removes all import leading to the src-old folder and also all unused refs

### PR DESCRIPTION
**Pull request by sulaimon23**

### CODE REVIEW

**Comment by JulianaSau** [comment]
Hi @sulaimon23, There are too many commits here considering you were only making changes to 4 files. Check your branch again and ensure you're pushing the correct things

**Comment by sulaimon23** [comment]
That happened because i had made my changes before pulling upstream..
@JulianaSau

**Comment by JulianaSau** [comment]
Well, there are stray commits in this pr. You can close it and open a fresh one with the correct commits after pulling changes from upstream and updating your remote repository

**Comment by sulaimon23** [comment]
@JulianaSau [https://github.com/zurichat/zc_main/pull/2592](url) closed this and re opened on that link

**Pull request closed without merging**
