### PR TITLE
ZUR-142 My PR updates member count spacing for create-workspace list and aligns the workspace name and  the right arrow

### PR DESCRIPTION
**Pull request by Kathalysth**
I Increased the **margin-top** on the member count container.
Screenshot (161)
Screenshot (163)

### CODE REVIEW

**Review by JulianaSau — APPROVED** [review]
Looks good

**Comment by billmal071** [comment]
Not done, move the arrow to the top also, let it be aligned with the name, not in the middle.

**Comment by Kathalysth** [comment]
updated arrow alignment with workspace name
Screenshot (165)

**Comment by billmal071** [comment]
@Kathalysth pull and push again.

**Comment by billmal071** [comment]
@Kathalysth  pull and push.

**Comment by Kathalysth** [comment]
> @Kathalysth pull and push again.

done that

**Comment by JulianaSau** [comment]
Pull and push again @Kathalysth

**Comment by Kathalysth** [comment]
> Pull and push again @Kathalysth

done

**Comment by JulianaSau** [comment]
Okay

**Pull request merged**
