### PR TITLE
Zuribot search bar functionality, Gateways Page

### PR DESCRIPTION
**Pull request by Lilianada**

### CODE REVIEW

**Comment by Lilianada** [comment]
https://linear.app/zuri/issue/ZC-2858/zuri-bot-search-bar-and-table

**Comment by Lilianada** [comment]
I do not have any inline styles in use. You can point me to the exact line you saw a style.

**Comment by Lilianada** [comment]
The inline styles you might see there is from someone else's work that had a conflict with mine because I had already carried out the task before pulling. So you can look for the person and request a change.

**Comment by Lilianada** [comment]
Please merge my work lemme be moving forward

**Comment by a11rew** [comment]
It shows in your [files changed](https://github.com/zurichat/zc_main/pull/2164/files) that you're adding the components with inline styles, what am I missing

**Comment by a11rew** [comment]
You have conflicts.

**Comment by Lilianada** [comment]
Why do they keep deleting <PrivateRoute path="/components/gateways" exact component={Gateways} /> from App.js? If it isn't routed how will my work display on site. Is there a reason for this?

**Comment by a11rew** [comment]
Lmaoo you sound frustrated as hell

**Pull request merged**
