### PR TITLE
ZUR-128: Redesign HomePage

### PR DESCRIPTION
**Pull request by tryraisins**
**Redesign the home page**
[screen-capture.webm](https://user-images.githubusercontent.com/78821732/201381023-b07d8ffb-c779-4664-a35c-87791ca7debe.webm)

### CODE REVIEW

**Review by JulianaSau — CHANGES_REQUESTED** [review]
The code looks good. My one concern is the inconsistency in the margin of the navigation bar component

image

**Comment by tryraisins** [comment]
> The code looks good. My one concern is the inconsistency in the margin of the navigation bar component
> 
> image

Thank you. I didn’t want to touch the navbar or footer code because they might be someone else’s issue/ticket

**Comment by JulianaSau** [comment]
I'll confirm if anyone is working on it

**Comment by JulianaSau** [comment]
You can just leave that change for now.

**Review by JulianaSau — APPROVED** [review]

**Comment by JulianaSau** [comment]
Pull changes again. I merged another pr

**Comment by tryraisins** [comment]
Done

**Pull request merged**
