### PR TITLE
Fixing Workspace dropdown items (Adding spaces)

### PR DESCRIPTION
**Pull request by marcellintacite**
Before : 
before

After : 
better

### CODE REVIEW

**Review by JulianaSau — CHANGES_REQUESTED** [review]
Code looks good. Something I'd suggest you could add is the padding on the workspace name is too small.

**Comment by marcellintacite** [comment]
I updated it! Thanks.

nouveau

**Comment by marcellintacite** [comment]
> Changes requested
Done with the new commit i made. Thank you.
nouveau

**Comment by JulianaSau** [comment]
This is the last fix. The spaces in between the sections should be uniform
image
Use the picture from Slack that i posted up there as a guide on the spacing

**Comment by marcellintacite** [comment]
Done with the task
update

**Comment by JulianaSau** [comment]
Pull updates from the dev branch so that I can merge

**Review by JulianaSau — APPROVED** [review]

**Pull request merged**
