### PR TITLE
ZUR 132: Remove the downloads page and links to it

### PR DESCRIPTION
**Pull request by Seundede**
Link to task: https://linear.app/zurichat2/issue/ZUR-132/remove-the-downloads-page-and-links-to-it

Before:
Screenshot 2022-11-12 at 00 48 07

After:
Screenshot 2022-11-12 at 00 47 05

Before:
Screenshot 2022-11-12 at 00 51 13
After:
Screenshot 2022-11-12 at 00 52 09

### CODE REVIEW

**Review by JulianaSau — CHANGES_REQUESTED** [review]
On the modal, Remove one line from there. Since the text download won't be there, there's no need for two dividers

**Comment by Seundede** [comment]
I am having an error pushing an update

**Comment by JulianaSau** [comment]
Yes. You have conflicts because someone else worked on the files before you got to merge.

Do you know how to resolve merge conflicts?

**Comment by Seundede** [comment]
> Yes. You have conflicts because someone else worked on the files before you got to merge.
> 
> Do you know how to resolve merge conflicts?

I have resolved conflicts

**Comment by JulianaSau** [comment]
Which issue?
Could you post a screenshot?

**Comment by Seundede** [comment]
I have removed the horizontal line but I had to do it through GitHub instead of my terminal. When you requested for changes to be made, I made the changes, made a commit and ran `git push origin feat/remove_download_links`. When that didn't work, I ran `git push`. They both gave the same error `fatal: Not possible to fast-forward, aborting.
husky - pre-push hook exited with code 128 (error)
error: failed to push some refs to 'https://github.com/Seundede/zc_main.git'`. I researched on fast-forward error and tried the solutions on force pushing, rebase and merging but I got different types of errors

**Comment by JulianaSau** [comment]
@Seundede Pull changes to your local repo and see if it works without breaking anything

If the git pull command doesn't work you can try `git pull upstream dev --rebase`

Al's add screenshots showing that you've removed that line.

**Review by JulianaSau — COMMENTED** [review]
@Seundede Pull changes to your local repo and see if it works without breaking anything. This is a big project so I can't merge if you don't confirm that it's working.

If the git pull command doesn't work you can try `git pull upstream dev --rebase`. Then if it works and you've ensured that everything is fine you can push the changes to your remote repository 

Also add screenshots showing that you've removed that line.

**Pull request closed without merging**
