### PR TITLE
feat[FE-24]: added sidebar cache on local storage

### PR DESCRIPTION
**Pull request by psalm987**
# Fixes Issue/Linear Ticket

( This could be an existing issue or a linear ticket )

Fixes FE-24 https://linear.app/team-chisel-hng9/issue/FE-24/zuri-chat-app-project-14

**My PR Closes #issue_number_here** or
**My PR Fixes Linear ticket FE-24**

# Changes proposed

## What were you told to do?

It takes too long to load the sidebar (left side). Cache the data using local storage so that it is instant once loaded. Send background request to update the info as needed (e.g over the open socket). Create protocol (if it does not exist) for sidebar updates.

## What did you do?

1) Created a cache sidebar utility that saves the sidebar information to the current workspace and the user email on the local storage [packages/main/src/utils/cache-sidebar.js](https://github.com/zurichat/zc_main/compare/dev...psalm987:zc_main:feat/sidebarcache?expand=1#diff-6a3f3555adef764c9f96643e11e706b31bb2e035b6e7c2c1e20a98e858fe10cd)
2) Implemented a useEffect hook that updates the saved sidebar data using the utility in file [packages/main/src/components/protected/sidebar/components/Sidebar.jsx](https://github.com/zurichat/zc_main/compare/dev...psalm987:zc_main:feat/sidebarcache?expand=1#diff-339198e6897aa2707e082af9f100278394e6e577a269bbf8c29471aeb87abea3)
3) Target the loading state reducer to display any saved sidebar data if no sidebar information is available, pending when the sidebar data is retrieved from the server-side [packages/main/src/components/protected/sidebar/reducers/sidebar.reducer.js](https://github.com/zurichat/zc_main/compare/dev...psalm987:zc_main:feat/sidebarcache?expand=1#diff-ba6e79ef7fc299fb27e4c1912cffcd3396d2915e9e72f2ed62f760523e2e91a2)

**Team Chisel - @Freckles**

# Check List (Check all the applicable boxes)

🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.

- [X] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I am making a pull request against the **dev branch** (left side).
- [X] My commit messages styles matches our requested structure.
- [X] My code additions will fail neither code linting checks nor unit test.
- [X] I am only making changes to files I was requested to.

# Screenshots/ Videos

image

### CODE REVIEW

**Comment by JulianaSau** [comment]
Hi @psalm987, could you please provide a video since this is a functionality?
Id like to see whether the sidebar relaods faster after the initial loading of the app

**Comment by psalm987** [comment]
@JulianaSau should the video be with and without the functionality implemented? Or just with the functionality?

**Comment by JulianaSau** [comment]
> @JulianaSau should the video be with and without the functionality implemented? Or just with the functionality?

With the functionality implemented

**Comment by psalm987** [comment]
https://user-images.githubusercontent.com/69042240/203911391-bebc25ba-1bdc-418e-bee9-ff5d8cf92565.mp4


Here is a screen recording of a hard refresh (with the shift key held), showing that the display of the sidebar is almost instantaneous, after the initial login action @JulianaSau

**Comment by psalm987** [comment]
@JulianaSau please would the **pending fix** label be a red flag or something?

**Pull request merged**
