### PR TITLE
ZUR-140 My PR centers the text on the left side of the icons in the create-workspace page

### PR DESCRIPTION
**Pull request by Uchechukwu10**
This PR changes the style in the CreateWorkspace component default page to enable the texts on the left of the icons be centered.

Solves the issue: https://linear.app/zurichat2/issue/ZUR-140/text-at-the-left-side-of-the-icons-in-the-create-workspace-should-be

Below is a screenshot of the initial look.
ZUR-140-initial

This is a screenshot of the fixed look where the left-sided texts are properly centered.
ZUR-140-fixed

This is the mobile view of the fixed page.
ZUR-140-mobile

### CODE REVIEW

**Comment by billmal071** [comment]
Pull to get new code.
then push again. Tell me when you do it.

**Comment by JulianaSau** [comment]
@billmal071 the conflicts are resolved.

**Comment by Uchechukwu10** [comment]
@billmal071 I have done as requested. I believe my PR is ready for review and hopefully merging.

**Comment by Uchechukwu10** [comment]
> Reference

Done

**Comment by Uchechukwu10** [comment]
> Pull to get new code. then push again. Tell me when you do it.

Done!

**Review by JulianaSau — APPROVED** [review]

**Review by JulianaSau — CHANGES_REQUESTED** [review]
Hi @Uchechukwu10. So i've confirmed your task and this is what you should do. Remove that image on the right side and mage the text that block of text on the left centered but in an aesthetically pleasing way. Ensure that the text matches the alignment of the page

**Comment by Uchechukwu10** [comment]
Just to confirm, the person working on it is removing the three images right?

**Comment by JulianaSau** [comment]
> Just to confirm, the person working on it is removing the three images right?

Yes. Those people images

**Comment by JulianaSau** [comment]
I've merged the pr that is removing the photos. Pull changes from the dev branch and start working on your task

**Comment by Uchechukwu10** [comment]
Alright, doing that right away

**Comment by Uchechukwu10** [comment]
I have centered the texts to align with the page, here's a screenshot of what I have so far.

zuri-fix

**Comment by JulianaSau** [comment]
The 'create a workspace'text can be one one line instead of two lines for bigger screens

**Comment by Uchechukwu10** [comment]
I have implemented the change

zuri-fix2

**Comment by JulianaSau** [comment]
Pull updates from the dev branch so that I can merge

**Review by JulianaSau — APPROVED** [review]

**Pull request merged**
