### PR TITLE
ZUR-129 My PR removes the unnecessary footer links in the Home Page

### PR DESCRIPTION
**Pull request by antomuangigitau**
### The homepage before the links are removed

Before-the-update-1
### Error on click to these links

Error-links
### After removing the links
The homepage now only has the relevant links

Homepage_necessary_links

### CODE REVIEW

**Comment by billmal071** [comment]
Pull to get latest code and push.

**Comment by antomuangigitau** [comment]
> Pull to get latest code and push.

Made the pull and push as requested

**Review by JulianaSau — CHANGES_REQUESTED** [review]
Hi @antomuangigitau, you've removed some needed links. Retain the WhyZuriChat link and change the text Plugin to Plugins

**Comment by antomuangigitau** [comment]
Hi @JulianaSau made the changes as requested.

### Add Why-Zuri-Chat-Link and change the text Plugin to Plugins

Added the why-zuri-chat link to the footer and corrected the plugin link text

add_link

**Review by JulianaSau — APPROVED** [review]

**Comment by JulianaSau** [comment]
Pull updates from dev branch so that I can merge

**Comment by antomuangigitau** [comment]
@JulianaSau Made the changes

**Pull request merged**
