### PR TITLE
Fix/contactpage issueId  = ZCG_12

### PR DESCRIPTION
**Pull request by Ademola101**
### Team-CARPENTER-SCALE
There was issue with the contact page as it display error message as user navigate to the contact page. This pull request fixes this issue.

### Error page (before)
localhost_9000_contact-us

### Our fix (after)
localhost_9000_contact-us (1)

### CODE REVIEW

**Comment by billmal071** [comment]
I can see white space on the right, fix it before it get's merged.

**Comment by Ademola101** [comment]
> I can see white space on the right, fix it before it get's merged.

Should another pull request be made after the fix? Or we continue on this one?

**Comment by AironDev** [comment]
image
As noted by @billmal071 

Fix it and push a commit, it should reflect on this current PR.

**Comment by Ademola101** [comment]
Thanks for the comment.

The new screen ]shot after the fix
Web capture_7-11-2022_21623_localhost

**Comment by Ademola101** [comment]
Thanks for the comment.

The new screen ]shot after the fix

Web capture_7-11-2022_21623_localhost

**Comment by Ademola101** [comment]
> image
> As noted by @billmal071 
> 
> Fix it and push a commit, it should reflect on this current PR.

Done. Please kindly review it

**Comment by JulianaSau** [comment]
@Ademola101 resolve the conflicts on your branch

**Comment by Ademola101** [comment]
Okay thanks. Right away

**Comment by Ademola101** [comment]
@JulianaSau the merge conflict has been resolved. Kindly review it.

**Review by JulianaSau — APPROVED** [review]
Looks good

**Comment by JulianaSau** [comment]
Please provide the link to the linear ticket that was assigned to you

**Comment by Ademola101** [comment]
> Please provide the link to the linear ticket that was assigned to you

The pull request is our group task. It is not an individual task on the linear ticket.
Task name ZCG_12

https://hng9.notion.site/558be084b6034facb47c1e31c13c7304?v=42b52cfffd9a4b7ba89548ac431e3a04&p=6eee6f9a52b24da5b01c0622b7880e45&pm=s

**Comment by JulianaSau** [comment]
> > Please provide the link to the linear ticket that was assigned to you
> 
> The pull request is our group task. It is not an individual task on the linear ticket. Task name ZCG_12
> 
> https://hng9.notion.site/558be084b6034facb47c1e31c13c7304?v=42b52cfffd9a4b7ba89548ac431e3a04&p=6eee6f9a52b24da5b01c0622b7880e45&pm=s

Thanks. That's alright. I just wanted to confirm something

**Comment by billmal071** [comment]
@Ademola101 you have conflicts. fix it.

**Comment by Ademola101** [comment]
> @Ademola101 you have conflicts. fix it.

Merge conflict fixed

**Comment by Ademola101** [comment]
> @Ademola101 you have conflicts. fix it.

Merge conflict fixed

**Comment by JulianaSau** [comment]
@Ademola101 pull and push changes from dev branch again

**Comment by Ademola101** [comment]
Done @JulianaSau

**Pull request merged**
