### PR TITLE
increase font size of join us

### PR DESCRIPTION
**Pull request by Ibrahim-Isah**
https://docs.google.com/spreadsheets/d/1AOe3gdinr6Y0M6GNvxof4hRaryMa5Xq9a0L-ZI1eZJM/edit#gid=1911449143

Link to document issue was assigned, number 19. No linear issue available. 
Increase font size of join us paragraph section

### CODE REVIEW

**Comment by Ibrahim-Isah** [comment]
@a11rew that change was requested by mark. He assigned me the task

**Comment by Ibrahim-Isah** [comment]
@a11rew Mark gave the instructions to just increase the font size with reference to other font on the page so I did

**Comment by Ibrahim-Isah** [comment]
Also please reopen my PR you closed concerning that Top Companies. The first guy was on landing page and mine was on About us page

**Comment by Ibrahim-Isah** [comment]
https://docs.google.com/spreadsheets/d/1AOe3gdinr6Y0M6GNvxof4hRaryMa5Xq9a0L-ZI1eZJM/edit#gid=1911449143

Link to document, I am number 19.


No linear issue for this

@ickynavigator

**Comment by ickynavigator** [comment]
a linear Issue is required for the promotion

**Comment by Ibrahim-Isah** [comment]
@ickynavigator This task is actually assigned to us by mark sha. Due to how small the task is, having a linear issue is not available and I shouldn't make one

**Comment by Ibrahim-Isah** [comment]
@pidoxy I don finish my task. No linear ticket for this task because it was direct assignment by Mark

**Pull request merged**
