### PR TITLE
Fix the top bar space bug

### PR DESCRIPTION
**Pull request by teamsandpaper01**

### CODE REVIEW

**Comment by billmal071** [comment]
Fix merge conflicts.

**Comment by JulianaSau** [comment]
@teamsandpaper01 resolve the conflicts on your branch

**Comment by JulianaSau** [comment]
@teamsandpaper01 add screenshots of the component that you changed before the fix and how it looks when you implement your changes

Also, indicate which linear ticked number you are working on in the description of your pr

**Comment by JulianaSau** [comment]
When you clear the conflicts and update the pr with required details you can reopen the pr

**Pull request closed without merging**
