### PR TITLE
Feat/login toggle password visibility feature team #einstein

### PR DESCRIPTION
**Pull request by tunji93**
After adding toggle password visibility functionality #168. Users can now choose to see their password by clicking the eye icon in the UI.   

https://user-images.githubusercontent.com/75486000/132096219-2f2029ac-2856-45a6-9e16-9e035c07b61c.mp4

### CODE REVIEW

**Comment by ickynavigator** [comment]
- resolve conflict 
- merge to review

**Comment by tunji93** [comment]
merge conflict has been resolved. 

> * resolve conflict
> * merge to review

**Comment by ickynavigator** [comment]
- merge to `review` branch

**Comment by tunji93** [comment]
> * merge to `review` branch

done

**Comment by sammiearchie77** [comment]
you've been the one messing with my code abi??? just imaging you still have the old design.... you people will not pull my code first

**Comment by ickynavigator** [comment]
conflicts

**Comment by ickynavigator** [comment]
conflicting with current logic of the page
make new branch and open a pr

**Pull request closed without merging**
