### PR TITLE
Edit User Profile picture  close #258

### PR DESCRIPTION
**Pull request by Solintin**
Pixel perfect  UI design of Edit user profile/picture  task completed.. 
Loom Screen Record as A proof =>  [Screen Record]((https://www.loom.com/share/9afc5cc611f64defb62509813e0ea1f4)

### CODE REVIEW

**Comment by AbaniwoM** [comment]
Pls resolve your conflicts. thanks

**Comment by Solintin** [comment]
Ok no problem i will resolve it

**Comment by sammiearchie77** [comment]
This branch has conflict
please fit

**Comment by seunbayo** [comment]
resolve conflicts

**Pull request closed without merging**
