### PR TITLE
ZUR-112 My PR changes the workspace dropdown items color when hovered.

### PR DESCRIPTION
**Pull request by Timi-cell**
Workspace dropdown items change to a white text when you hover.
ticket

### CODE REVIEW

**Comment by JulianaSau** [comment]
@Timi-cell please provide screenshots of the page component before and after your changes

**Comment by Timi-cell** [comment]
I already added a screenshot… please check.

**Comment by Timi-cell** [comment]
@JulianaSau

**Comment by Timi-cell** [comment]
Or do you mean screenshots of how it looks like on google before and after the change I made? @JulianaSau ... I just want to be sure

**Comment by JulianaSau** [comment]
> Or do you mean screenshots of how it looks like on google before and after the change I made? @JulianaSau ... I just want to be sure

Yes. A picture of the page. Not the code

**Comment by Timi-cell** [comment]
Okay

**Comment by Timi-cell** [comment]
Before the change

https://user-images.githubusercontent.com/76186590/201440747-fc6ddab4-3194-4530-87c9-e7d7557e6f81.mp4

**Comment by Timi-cell** [comment]
After the change

https://user-images.githubusercontent.com/76186590/201440868-3047c306-a7c8-45a0-a2f5-b3d2acc39f44.mp4

**Comment by Timi-cell** [comment]
@JulianaSau  Done.

**Comment by JulianaSau** [comment]
The text on tools and switch workspace is glitching and not changing until you hover over the text. They should change color when the button is hovered over regardless of whether the cursor is over the text or not.
I hope you're understanding what I'm saying

**Comment by Timi-cell** [comment]
Yes I understand, will work on it right now @JulianaSau

**Comment by Timi-cell** [comment]
I have done the necessary changes... @JulianaSau 

https://user-images.githubusercontent.com/76186590/201478460-51852501-e65f-43c3-a65f-3d4d4e31a707.mp4

**Comment by Timi-cell** [comment]
Please check  @JulianaSau

**Review by JulianaSau — APPROVED** [review]

**Pull request merged**
