### PR TITLE
Feat/userpreference

### PR DESCRIPTION
**Pull request by agkayster**
Implemented Notifications page under User preference.

### CODE REVIEW

**Comment by a11rew** [comment]
You have conflicts.

**Comment by ickynavigator** [comment]
60???

**Comment by agkayster** [comment]
I am not overwriting anything, it is asking me to accept incoming code and that is what I am doing. How are these conflicts even coming up for someone whose component is User preference?

**Comment by ickynavigator** [comment]
the app works fine for me too
are you pulling from main or dev?

**Comment by agkayster** [comment]
Screenshot 2021-10-13 at 22 29 41
>

Look at these screenshots, there are errors in one of the codes that is throwing up an error which does not allow me go to login, how is that possible?

**Comment by agkayster** [comment]
@ickynavigator You must have just fixed the last screen shot because that was what I pulled and it kept on giving errors that I could not login in to zuri chat, so it definitely shows it is not from my end.

**Comment by agkayster** [comment]
@a11rew I would try that but it has always worked fine on my local branch as well before I push and create PR.

**Comment by agkayster** [comment]
@a11rew Yes, and if i check properly, someone had messed with our CSS Styling for Notification page which forced me to roll back to a good code I had committed. What is wrong with that?

**Comment by agkayster** [comment]
@ickynavigator if other pages were fine, why is there the merge conflict that tells me to accept incoming code. which is simply what I did.

**Pull request closed without merging**
