### PR TITLE
ZUR-102 Updated the padding for the icon in the search bar in the status modal

### PR DESCRIPTION
**Pull request by Xoned20**
I updated the padding for the icon in the search bar in the status modal, setting the top, bottom, left, and right padding to 0px.

https://linear.app/zurichat2/issue/ZUR-102/fix-smiley-icon-padding-in-the-search-bar-in-the-status-modal

Screenshot 2022-11-10 220345
Screenshot 2022-11-10 220416
Screenshot 2022-11-10 221047

### CODE REVIEW

**Review by JulianaSau — APPROVED** [review]

**Comment by JulianaSau** [comment]
Change the title of your pr to be more descriptive @Xoned20

**Comment by Xoned20** [comment]
Ok, changed the title already @JulianaSau , Thank you

**Review by JulianaSau — APPROVED** [review]

**Comment by billmal071** [comment]
Pull new code and push again.

**Comment by Xoned20** [comment]
Done @billmal071, Thank you

**Pull request merged**
