### PR TITLE
Add the option of French on preference page language page and remove the spellcheck settings

### PR DESCRIPTION
**Pull request by somtookaforr**
Add the option of French on preference page language page and remove the spellcheck settings

Task by Mark
Slack username is Sensei

### CODE REVIEW

**Comment by ickynavigator** [comment]
why are you altering more than what you stated in the PR

**Comment by pidoxy** [comment]
your PR is not up to date pull and update

**Comment by Wavist** [comment]
> your PR is not up to date pull and update

I just pulled and updated

**Comment by Wavist** [comment]
> why are you altering more than what you stated in the PR

Nothing else was altered. I had to remove the setting and update the language as stated

**Pull request closed without merging**
