### PR TITLE
ZUR-104 My PR patches distortions in the set status modal.

### PR DESCRIPTION
**Pull request by WeeNeeBee**
**Link to issue: https://linear.app/zurichat2/issue/ZUR-104/patch-distortions-in-the-scrollable-container-and-the-modal-title-in**

**Before:**

- Set status title wasn't aligned properly.

before

**After:**

- Set status title aligned properly.

after

**Tab responsive:**
tab

**Mobile responsive:**
mobile

### CODE REVIEW

**Comment by JulianaSau** [comment]
There's someone already working on the save inactive button. So you may remove any changes made to the styling of the button as it may bring merge conflicts.

Also the margin on the header is not uniform. if you check well, the space after the button is bigger than the space before the word 'Set'

**Comment by WeeNeeBee** [comment]
> There's someone already working on the save inactive button. So you may remove any changes made to the styling of the button as it may bring merge conflicts.
> 
> Also the margin on the header is not uniform. if you check well, the space after the button is bigger than the space before the word 'Set'

Changes have been implemented - "Set status" title properly aligned and the inactive button section reverted.

**Review by JulianaSau — APPROVED** [review]

**Comment by JulianaSau** [comment]
Pull new changes from dev so that I can merge

**Comment by WeeNeeBee** [comment]
> Pull new changes from dev so that I can merge

Done.

**Pull request merged**
