### PR TITLE
ZUR-98 My PR adds a search button and search icon to the global search.

### PR DESCRIPTION
**Pull request by 64eyes**
# Fixes Issue

**My PR Fixes ID-98**

# Changes proposed

## What were you told to do ?

Add a search button and search icon to the global search.

## What did you do ?

I added a Search_icon image to the images folder which I added to the search button I created in the global search.

# Check List (Check all the applicable boxes)

🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos

What the app looked like before
Screenshot (41)
What the app look like now
Screenshot (42)

### CODE REVIEW

**Review by JulianaSau — CHANGES_REQUESTED** [review]
I don't think there is a need to add another asset to the project when you can easily use an icon from the `react-icons` package installed in the project. delete the image and use an icon instead

**Comment by JulianaSau** [comment]
Als, edit te title of your pr to include your linear ticket number like the other prs

**Comment by 64eyes** [comment]
I'll do that boss. Thanks.

**Comment by 64eyes** [comment]
I've attended to all your comments boss. I hope the PR would be merged this time around. Thanks boss.

**Review by JulianaSau — APPROVED** [review]

**Pull request merged**
