### PR TITLE
(Team Einstein) adds loading component to close #502

### LINKED ISSUE #502: Loading component
Create a component that is displayed when the app is in a loading state

### PR DESCRIPTION
**Pull request by KingsleyIbe**
Hello team!

Kindly review and merge my work. I have implemented issue #502 . Herein are screenshots of my project and a [live preview link.](https://kingsleyibe.github.io/zuriLoading/)
Loading css
Loading js
Spinner js

Thank you

### CODE REVIEW

**Comment by ickynavigator** [comment]
- merge into `review` branch
- format code (you can run `yarn format` to do that)

**Comment by ickynavigator** [comment]
- resolve conflicts

**Review by KingsleyIbe — COMMENTED** [review]
Kindly confirm that conflicts have been resolved

**Comment by ickynavigator** [comment]
- format code (you can run yarn format to do that)
- readd the marketplace route you removed

**Comment by KingsleyIbe** [comment]
- Code has been formatted
- marketplace route wasn't removed, please check again.

**Comment by ickynavigator** [comment]
check the app.js file in your files changed section.

**Comment by KingsleyIbe** [comment]
Apologies.
That has been corrected. Please confirm.

**Pull request merged**
