### PR TITLE
ZUR-139: Add a why zuri chat page

### PR DESCRIPTION
**Pull request by abdulmalikyusuf**
ZUR-139

Here's my PR. I added a route to the **_Why Zuri Chat page_**. I copied the _WhyZuriChat_ folder from **_src-old_** to **_src_** and also copied its file dependencies.

### CODE REVIEW

**Review by JulianaSau — APPROVED** [review]

**Comment by JulianaSau** [comment]
Hi @abdulmalikyusuf, pull changes from the dev branch and push again so that I can merge

**Comment by abdulmalikyusuf** [comment]
Ok would do that

**Comment by abdulmalikyusuf** [comment]
@JulianaSau I have done that

**Comment by JulianaSau** [comment]
@abdulmalikyusuf pull and push the changes again

**Comment by abdulmalikyusuf** [comment]
I added an additional features where the page scrolls to the top after navigation. Thanks

**Comment by JulianaSau** [comment]
okay. Great work

**Comment by abdulmalikyusuf** [comment]
> okay. Great work

Thank you

**Pull request merged**
