### PR TITLE
Fix: Sidebar Faster Loading ZUR-144

### PR DESCRIPTION
**Pull request by ElemaGp**
Made the sidebar contents load faster by importing the sidebar component directly, not "lazily", so that sidebar contents are fetched and then displayed after loading.

https://user-images.githubusercontent.com/110695436/201439128-b8bbcf7c-47c5-4934-9f90-6ff754bdfc41.mp4

### CODE REVIEW

**Comment by JulianaSau** [comment]
Hi @ElemaGp, since your pr is an issue of performance, you could record a video instead of a screenshot so that we can see how fast it is now in action.

**Comment by JulianaSau** [comment]
Hi These were some of the suggestions given

> You can cache the content in the sidebar or you can make the initial loader wait until the whole data is fetched

Did you try these too? I think your fix works but only to an extent. On Slack, it usually displays the UI and loaders where the content should be. So you can try adding these suggested fixes to maximize the performance and user experience.

**Comment by ElemaGp** [comment]
Added the "Loading..." UI using "Suspense" and the sidebar skeleton for the contents while loading, for a better user experience.

Also, imports using "lazily" makes the program display the component while still fetching which previously made the sidebar load very slowly.

Importing directly now ensures that the data is fetched first, making the sidebar load much faster.
[sidebar faster loading.webm](https://user-images.githubusercontent.com/110695436/201543515-eebf00fe-8f9c-4326-afaa-979fdda121bf.webm)

**Comment by JulianaSau** [comment]
Great work @ElemaGp. Pull changes from the dev branch and push to your repository

**Comment by JulianaSau** [comment]
Your branch is 6 commits behind

**Review by JulianaSau — APPROVED** [review]

**Pull request merged**
