### PR TITLE
Feat/get user details

### PR DESCRIPTION
**Pull request by Temilade05**
Add logic and route to get user details.

### CODE REVIEW

**Review by Robertito1 — CHANGES_REQUESTED** [review]
Looks great 👍, but can you get rid of all the `.idea/` files?

**Comment by Temilade05** [comment]
Completed

**Review by Robertito1 — APPROVED** [review]
Perfect!

**Review by Robertito1 — APPROVED** [review]

**Comment by Temilade05** [comment]
Please why did you close my PR?

**Pull request closed without merging**
