### PR TITLE
ZUR-121 fixed the contact us page in the login form

### PR DESCRIPTION
**Pull request by nnaemekaxi**
Link: https://github.com/nnaemekaxi/zc_main/tree/contact-us-page
Linear ID: ZUR-121 The contact page in the login form is not working 

Bugs Fixed: async and await added (lines 34 & 35) of ContactFormContainer

VS Code
Browser

### CODE REVIEW

**Comment by nnaemekaxi** [comment]
https://github.com/nnaemekaxi/zc_main/tree/contact-us-page

**Comment by nnaemekaxi** [comment]
https://github.com/nnaemekaxi/zc_main/tree/contact-us-page

**Comment by billmal071** [comment]
Add the linear id and fix conflicts.

**Review by JulianaSau — APPROVED** [review]

**Comment by JulianaSau** [comment]
Your task is to fix the displaying of the contact page. Make reference to the pr #2501 to see how they were able to implement it

**Review by JulianaSau — CHANGES_REQUESTED** [review]
Implement the above changes

**Review by JulianaSau — APPROVED** [review]

**Comment by JulianaSau** [comment]
Update your pr with changes from the dev branch so that i can merge it

**Comment by nnaemekaxi** [comment]
changes pulled from dev branch
working tree clean

**Comment by JulianaSau** [comment]
Pull again. I merged another pr after you updated

**Comment by nnaemekaxi** [comment]
done

**Pull request merged**
