### PR TITLE
Feat/status badge component

### PR DESCRIPTION
**Pull request by Sharpmind015**
Build status badge beside display image #422 

Screenshot:
status

<a href="https://zuri.chat/" target="_blank">Live link</a>

### CODE REVIEW

**Comment by markessien** [comment]
Nothing like that on live

**Comment by Sharpmind015** [comment]
@markessien for it to be reflected on the live link, it has to be merged first

**Comment by Sharpmind015** [comment]
@markessien it hasn't been merged to the develop branch yet.

**Comment by Sharpmind015** [comment]
> Nothing like that on live

<a href="https://zuri.chat/home" target="_blank">Live link</a>

**Pull request merged**
