### PR TITLE
Remove people/channel modal

### PR DESCRIPTION
**Pull request by afaraitsulaimon**
# Fixes Issue

( This could be an existing issue or a linear ticket )

**My PR Closes #issue_number_here** or
**My PR Fixes ID-linear_ticket_number_here**

# Changes proposed

## What did you do ?

# Check List (Check all the applicable boxes)

🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title and description of the PR is clear and explains the approach.
- [ ] I am making a pull request against the **dev branch** (left side).
- [ ] My commit messages styles matches our requested structure.
- [ ] My code additions will fail neither code linting checks nor unit test.
- [ ] I am only making changes to files I was requested to.

# Screenshots/ Videos

### CODE REVIEW

**Comment by afaraitsulaimon** [comment]
Here is the Linear ID - ZUR-172

**Comment by JulianaSau** [comment]
Fill in the details in your pr. Youve not explained what changes youre making nor posted screenshots of beofre your changes and after your changes @afaraitsulaimon

**Comment by afaraitsulaimon** [comment]
remove memeber from channel code implemented

modal added

I worked on Add the ability to remove people via the channels modal - Linear ID - ZUR-172

or you want me to make a new PR

**Comment by afaraitsulaimon** [comment]
theFunctionBefore

before onclick on remove button

Here is how the code look like before

**Comment by JulianaSau** [comment]
Hi @afaraitsulaimon. Add a video showing how removing people from channels works

**Comment by afaraitsulaimon** [comment]
okay

**Pull request closed without merging**
