### PR TITLE
[ZCG_13] Fix the About page issues with the styling

### PR DESCRIPTION
**Pull request by tochibedford**
Handles ticket [ZCG_13], and fixes issue #2507

### CODE REVIEW

**Comment by tochibedford** [comment]
Preview:
Screenshot (58)
Screenshot (59)
Screenshot (60)

**Comment by billmal071** [comment]
Fix conflicts to get your code merged.

**Comment by tochibedford** [comment]
@billmal071 All done

**Comment by billmal071** [comment]
Alright, merging....

**Pull request merged**
