### PR TITLE
Feat/set status tag feature

### PR DESCRIPTION
**Pull request by Ayodejioladimeji**
Implemented the status tag feature, click on the image on the top right bar to see the dropdown, 
https://set-status-tag.netlify.app
This is a temporary link to see the output

Below is the figma link
einstein

Below is the implementation
einstein2

### CODE REVIEW

**Comment by AbaniwoM** [comment]
> Implemented the status tag feature, click on the image on the top right bar to see the dropdown,
> https://set-status-tag.netlify.app
> This is a temporary link to see the output
> 
> Below is the figma link
> einstein
> 
> Below is the implementation
> einstein2

**Comment by AbaniwoM** [comment]
There are some conflicts in your work. Pls check. thanks

**Comment by markessien** [comment]
No live testing link

**Comment by Ayodejioladimeji** [comment]
Live testing link is in the PR informations
https://set-status-tag.netlify.app

**Pull request closed without merging**
