### PR TITLE
ZUR-169 Fix UI of add files modal on message input component

### PR DESCRIPTION
**Pull request by Musab1258**
# Fixes Issue

My PR Fixes ID-169

# Changes proposed

## What were you told to do ?

Fix UI of add files modal on message input component

## What did you do ?

I [styled](https://github.com/Musab1258/zc_main/blob/feat/sendfile/packages/ui/src/message-pane-input/components/SendFile.module.css) the add files modal to make each options be on a line. 
I added an hover property to each of the options.
I also implemented the ability to allow users to upload a file from their local computer using the Ctrl+U keys.
I ensured that I used colors that were consistent with the styling of the app
 
# Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos

What the site looked like before

ZUR-169

After I added my code

ZUR-169-done

### CODE REVIEW

**Comment by JulianaSau** [comment]
@Musab1258 let the modal pop up where the button is. It should behave like a popover. Why is it popping up on the right when the button is on the left

**Comment by JulianaSau** [comment]
And ensure that it is responsive across the bigger screens

**Review by JulianaSau — CHANGES_REQUESTED** [review]
I've left comments above. Check them out

**Comment by Musab1258** [comment]
This is how it looks now.

ZUR-169-done2

**Review by JulianaSau — APPROVED** [review]

**Comment by Musab1258** [comment]
@JulianaSau , It was nice working with you.
Thanks a lot.

**Pull request merged**
