### PR TITLE
Chore/remove blog

### PR DESCRIPTION
**Pull request by amarealcoder**
**My PR Fixes ID-linear_ticket_number ZUR-148**

# Changes proposed

 Remove the blog page and the help links that redirect to it

## What did you do ?

- Deleted the ZuriChatBlog file.
- Deleted the ZurichatBlog CSS file.
- Deleted the blog link at the footer.js file.

zuriWithBlog
ZuriWithoutBlog

# Fixes Issue
  

( This could be an existing issue or a linear ticket )

**My PR Closes #issue_number_here** or
**My PR Fixes ID-linear_ticket_number_here**

# Changes proposed

## What did you do ?

# Check List (Check all the applicable boxes)

🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [ ] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [ ] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos

### CODE REVIEW

**Comment by billmal071** [comment]
I feel like I've already seen this and it has been merged already.

**Comment by JulianaSau** [comment]
@billmal071 I think that one was just removing the blog link from the footer. This one is doing away with the whole blog page entirely

**Comment by JulianaSau** [comment]
Also, pull recent updates from the `dev` branch. Always ensure that your branch is up to date @amarealcoder

**Comment by amarealcoder** [comment]
@JulianaSau You marked it pending fix. Please, what I'm I supposed to fix for the pull request?

**Comment by JulianaSau** [comment]
Update your branch. I can't merge if your branch is not up to date with the dev branch

**Comment by amarealcoder** [comment]
ok

**Comment by amarealcoder** [comment]
The source branch has no conflict with the target branch. Will I still need to rebase? @billmal071 @JulianaSau

**Pull request closed without merging**
