### PR TITLE
ZUR-192 My pull request fixes translations issue on the download page

### PR DESCRIPTION
**Pull request by webala**
This issue is fixed by creating translation files for the different download pages ie DownloadDesktop, DownloadMobile, DownloadIos, DownloadMac and DownloadWindows. The translation files include translations for the different available languages.

### CODE REVIEW

**Comment by webala** [comment]
Screenshot from 2022-11-11 08-13-43
Screenshot from 2022-11-11 08-13-25
Screenshot from 2022-11-11 08-13-17

**Comment by JulianaSau** [comment]
Looks good @webala

**Comment by JulianaSau** [comment]
resolve conflicts on your branch @webala

**Pull request merged**
