### PR TITLE
added password preference close #427

### LINKED ISSUE #427: Password preference
a password must be a mixture of numbers,letters and special characters

### PR DESCRIPTION
**Pull request by ickynavigator**
Added a function to check if the password is of a valid length as well as checking if it contains a
- number
- special character
- lowercase letter
- uppercase letter

closes [issue 427](https://github.com/zurichat/zc_main/issues/427#issue-981965804)

### CODE REVIEW

**Comment by ickynavigator** [comment]
slack username - `ObiFortune`

**Comment by AbaniwoM** [comment]
pls resolve conflicts

**Comment by ickynavigator** [comment]
I have resolved them

**Comment by markessien** [comment]
No testing link

**Pull request merged**
