### PR TITLE
ZUR-178 Persist last view

### PR DESCRIPTION
**Pull request by dyCodes**
# Fixes Issue

**My PR Fixes ID-178**

# Changes proposed

## What were you told to do ?

Persist the last view i was in. whether a chat or a plugin.

## What did you do ?

Persist chat state for each room to sessionStorage.

# Check List (Check all the applicable boxes)

🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I am making a pull request against the **dev branch** (left side).
- [X] My commit messages styles matches our requested structure.
- [X] My code additions will fail neither code linting checks nor unit test.
- [X] I am only making changes to files I was requested to.

# Screenshots/ Videos

https://user-images.githubusercontent.com/58990930/202037829-e7f5c944-bcb9-4127-ae92-16d74859e6a3.mp4

### CODE REVIEW

**Comment by JulianaSau** [comment]
Hi @dyCodes, this feature meant that when a person logs out when they were viewing the general channel, when they log in again, they should be redirected to the general channel instead. Or another case could be if I closed my tab when I was viewing the music plugin, when I log in, I should be redirected to the music plugin, where I was when I logged out

**Review by JulianaSau — CHANGES_REQUESTED** [review]
I've left a comment above. Check it

**Comment by JulianaSau** [comment]
Send a video showing that this feature works @dyCodes

**Comment by dyCodes** [comment]
https://user-images.githubusercontent.com/58990930/202170498-8209f624-bd58-4037-97e3-5fa79f1c9fdc.mp4

**Pull request merged**
