### PR TITLE
Additional Language support  via Google Translator added [LANGUAGE PROJECT]

### PR DESCRIPTION
**Pull request by AironDev**
image

### CODE REVIEW

**Comment by AironDev** [comment]
> This seems like it would have far reaching implications, what with the overlay iframe. The jquery import would have to be taken out definitely. Also, how does this play out in situations where individual plugins need control over the translated output.

JQuery will be replaced with Vanilla Js,
Secondly, I don't think Iframe injected will affect plugin interactions, since it does not replace the dom.  -
Howbeit - We can only get to know by testing it out

**Comment by pidoxy** [comment]
How are translations for other pages done? Do they go this route?

There should be a better means

**Comment by AironDev** [comment]
@pidoxy - This was intended to give more language support via google automatic translator.

**Comment by AironDev** [comment]
@a11rew @pidoxy

**Pull request merged**
