### PR TITLE
FEAT(FEC-79)

### PR DESCRIPTION
**Pull request by Ollarr**
# Fixes Issue/Linear Ticket
In this PR, I
--FEC-79-adjust-left-nav-bar-on-termsconditions
--adjust left nav bar in the terms and condition page.
--https://linear.app/mechanic-team-prybar/issue/FEC-79/adjust-left-nav-bar-on-termsandconditions-to-fit-design#comment-9fd88a6a
Screenshot (47)

### CODE REVIEW

**Comment by JulianaSau** [comment]
@Ollarr This PR can not be merged. There is no description of what you've done and no screenshots to show how the app looks after your changes. Please check the other open pull requests to see the format used and edit your PR description accordingly. Refer to the [contribution guidelines](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) of this repo

**Comment by JulianaSau** [comment]
and update your PR title to include the linear ticket link and the title of the changes you're making

**Review by ickynavigator — CHANGES_REQUESTED** [review]
Address the comments made by @JulianaSau 
Your PR is not descriptive at all

**Review by ickynavigator — APPROVED** [review]
try and add a before picture as well

**Review by JulianaSau — APPROVED** [review]

**Pull request merged**
