### PR TITLE
 [ZCG_23] Fix the drop down page overlapping by team mechanic-team-gear

### PR DESCRIPTION
**Pull request by Cospis**
the task given to mechanic-team-gear on HNG internship

### CODE REVIEW

**Comment by billmal071** [comment]
Provide evidence of workdone.

**Comment by Cospis** [comment]
> Provide evidence of workdone.

image

**Comment by Cospis** [comment]
@billmal071 please what's next to do?

**Comment by Cospis** [comment]
@billmal071 I already added the prove

**Pull request closed without merging**
