### PR TITLE
Ticket ID ZCG_5: Remove the All DMs functionality

### PR DESCRIPTION
**Pull request by Chizycodes**
Before: 
Screenshot from 2022-11-06 20-14-58

After:
Screenshot from 2022-11-06 20-27-44

### CODE REVIEW

**Comment by JulianaSau** [comment]
@Chizycodes Resolve the conflicts on your branch

**Comment by JulianaSau** [comment]
Could you add a direct link to the linear issue so i can view it and what it entails @Chizycodes

**Comment by Chizycodes** [comment]
> Could you add a direct link to the linear issue so i can view it and what it entails @Chizycodes

It's not a linear issue. It's an issue on notion my team chose for the first team task. https://hng9.notion.site/558be084b6034facb47c1e31c13c7304?v=eee7ed5d052544b6a615a486b9ef3ba5&p=64883816543b440aacc9830aee5e7ed8&pm=s

**Comment by Chizycodes** [comment]
> Could you add a direct link to the linear issue so i can view it and what it entails @Chizycodes

It's not a linear issue. It's an issue on notion my team chose for the first team task. https://hng9.notion.site/558be084b6034facb47c1e31c13c7304?v=eee7ed5d052544b6a615a486b9ef3ba5&p=64883816543b440aacc9830aee5e7ed8&pm=s

**Comment by JulianaSau** [comment]
Okay. So for now we're holding of on merging the team tasks. We're merging individual frontend tasks first

**Pull request merged**
