### PR TITLE
ZUR-193 : Fix the translation language on the button (download page)

### PR DESCRIPTION
**Pull request by mo-renike**
download_page

### CODE REVIEW

**Comment by billmal071** [comment]
You have conflicts.

**Comment by mo-renike** [comment]
Fixed

**Review by JulianaSau — APPROVED** [review]

**Comment by billmal071** [comment]
What is the linear id?

**Comment by mo-renike** [comment]
> What is the linear id?

ZUR-193

**Comment by JulianaSau** [comment]
@mo-renike pull from dev, resolve conflicts then tag me

**Comment by mo-renike** [comment]
> @mo-renike pull from dev, resolve conflicts then tag me

Done

**Pull request merged**
