### PR TITLE
FAQ section

### PR DESCRIPTION
**Pull request by DonSmog**
FAQ drop-down
drop down <br>
iPad View
iPad view<br>
Mobile view
mobile view<br>
PC View
PC View

### CODE REVIEW

**Comment by pidoxy** [comment]
You have 18 files changed, please fix this

**Comment by AbaniwoM** [comment]
Pls resolve conflicts

**Comment by pidoxy** [comment]
the accordion is also not according to design


Screenshot 2021-08-31 at 13 46 55

**Comment by AbaniwoM** [comment]
Choose another issue  Sent from Mail for Windows From: IDOKO EMMANUELSent: Tuesday, August 31, 2021 1:49 PMTo: zurichat/zc_mainCc: Michael Abaniwo; State changeSubject: Re: [zurichat/zc_main] FAQ section (#565) the accordion is also not according to design—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
