### PR TITLE
Reduce the size of the big header area on the marketplace page

### PR DESCRIPTION
**Pull request by Davidlloyd8**

### CODE REVIEW

**Comment by Davidlloyd8** [comment]
https://docs.google.com/spreadsheets/d/1AOe3gdinr6Y0M6GNvxof4hRaryMa5Xq9a0L-ZI1eZJM/edit#gid=1911449143


done according to the sheet line 9

**Comment by a11rew** [comment]
The header banner takes up a substantial amount of space on the marketplace page. Especially on mobile screens. So that's what you have to fix. But as always you should speak to the assigner of the task for the final word on what exactly your task is.

**Comment by Davidlloyd8** [comment]
No Reply

**Comment by Davidlloyd8** [comment]
Are talking the the width rounded border of cards

**Comment by a11rew** [comment]
@Davidlloyd8 you'd have to get clarification from the assigner.

**Comment by Davidlloyd8** [comment]
Okay

**Comment by Davidlloyd8** [comment]
@a11rew

**Comment by Davidlloyd8** [comment]
@a11rew

**Comment by a11rew** [comment]
image
Still takes up over 80vh

**Comment by Davidlloyd8** [comment]
Are you speaking about the height or width

**Comment by Davidlloyd8** [comment]
@a11rew

**Comment by Davidlloyd8** [comment]
Can it be merge now
and go live 
i need to fill sheet

**Comment by Davidlloyd8** [comment]
@a11rew

**Comment by a11rew** [comment]
Changes are pushed to staging and production in cycles. It'll be added in the next cycle.

**Comment by Davidlloyd8** [comment]
ok

**Pull request merged**
