### PR TITLE
Fix(ZUR-7): Fix and Improve search functionality

### PR DESCRIPTION
**Pull request by jeckdix**
# Added the ability to view search results by type and improved the search component UI 

**My PR Fixes ID: ZUR-7 for team clutch (Frontend)
- https://linear.app/hng-team-clutch/issue/ZUR-7/integrate-search-functionality-on-zuri-chat 

# Changes proposed

## What were you told to do?
<!- I was required to make search functionality work 

## What did you do?
- Added the ability to view search results by type (added tabs)
- Created different cards for search type
- Improved the result card UI 
- Fixed styling issues for responsiveness
- Removed redundant lines of code

# Check List (Check all the applicable boxes)

🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/ Videos
https://www.loom.com/share/d5245f06dbd040538f1d4d04bc6cd7e7

### CODE REVIEW

**Comment by JulianaSau** [comment]
Why does your OR have stray commits😅. It should only contain commits with changes that you made

**Comment by JulianaSau** [comment]
Either create a new or fix this one

**Comment by jeckdix** [comment]
@JulianaSau pls that can be fixed when merging by squashing the commits into one

**Comment by JulianaSau** [comment]
@jeckdix I'm not taking chances with this one. We've finally fixed errors on the repo and these stray commits are very old commits from that period of time when we had errors.

**Pull request closed without merging**
