### PR TITLE
ZUR-99:feat: Added the hover tooltip for the status

### PR DESCRIPTION
**Pull request by Beyond-Logic**
What does this PR do?

This PR fixes: [https://linear.app/zurichat2/issue/ZUR-99/add-the-hover-tooltip-for-the-status](https://linear.app/zurichat2/issue/ZUR-99/add-the-hover-tooltip-for-the-status)

Added hover tooltip for the status at the top bar in the profile

profile-status

profile-status-tooltip

Position tool tip under profile icon:

profile-status-tooltip1

profile-status-tooltip2

### CODE REVIEW

**Comment by JulianaSau** [comment]
Hi @Beyond-Logic, could this tooltip be right under the profile icon? Where it is currently its right on top of the languages button, which isn't good user experience

**Comment by Beyond-Logic** [comment]
@JulianaSau I have made the changes

**Comment by JulianaSau** [comment]
Great work. One more thing, it kind of looks like a button. Could you reduce the height a bit so it looks like more of a suggestion than something that can be clicked?
Also, I think it could have a kind of arrow at that top, like normal tooltips have.

**Comment by Beyond-Logic** [comment]
@JulianaSau Thanks. 
I have made some adjustments: 

- Positioned the tooltip under the profile icon . 

- Adjusted the width and height with some padding.

**Review by JulianaSau — APPROVED** [review]

**Comment by Beyond-Logic** [comment]
Thanks. @JulianaSau

Also, I Noticed my vscode formatted the TopNavBar.module.css file when I added my css.

**Comment by JulianaSau** [comment]
That's alright. As long as it didn't affect anything it's all good

**Comment by Beyond-Logic** [comment]
@JulianaSau Thanks

**Pull request merged**
