### PR TITLE
Converted Header in design to code #491

### PR DESCRIPTION
**Pull request by agkayster**
#491 
@pidoxy 
Team Aristotle

Figma link: https://www.figma.com/file/kWxC7b8vRWT8X6RgRCGtsc/Aristotle-Workspace
Live link: https://header-app.netlify.app/#/

I implemented the conversion of Header in the Figma design to code using React, Bootstrap, and CSS module. I also ensured it was responsive on Mobile, Tablet, and Desktop media formats.

Mobile View
image

Tablet View
image

Desktop View
image

### CODE REVIEW

**Comment by sammiearchie77** [comment]
your branch has conflict, please fix

**Comment by agkayster** [comment]
> your branch has conflict, please fix

Good day Sir, I have fixed it

**Comment by sammiearchie77** [comment]
seen

**Comment by sammiearchie77** [comment]
What group are you sir?

**Comment by agkayster** [comment]
My group is: Aristotle.Sent from my Galaxy
-------- Original message --------From: Samuel Archibong ***@***.***> Date: 02/09/2021  08:45  (GMT+01:00) To: zurichat/zc_main ***@***.***> Cc: Ejike ***@***.***>, Author ***@***.***> Subject: Re: [zurichat/zc_main] Converted Header in design to code #491 (#647) 

What group are you sir?



On Thu, Sep 2, 2021, 8:22 AM Samuel Chinonso Archibong <

**Pull request merged**
