### PR TITLE
Fixed issue #613 by Ofili chukwuemeka - Team Einstein

### PR DESCRIPTION
**Pull request by chumex412**

### CODE REVIEW

**Comment by ickynavigator** [comment]
- add a description

**Comment by chumex412** [comment]
Wrote the logic for making the visibility icon appear when the user starts typing in the input field for password and also the logic for when the user wants to know if what he/she typed was correct by clicking the icon to toggle between showing or hiding the password actual characters. I also created/added custom reducer hook for reusability and managing state relating to password visibility.

**Comment by ickynavigator** [comment]
- merge to review branch

**Comment by ickynavigator** [comment]
- merge to review branch

**Pull request closed without merging**
