### PR TITLE
ZUR-130 My PR makes the footer social icon the same

### PR DESCRIPTION
**Pull request by bimbo-ade**
This PR makes the social icon in the footer same

before-footer-edit

after-footer-edit

### CODE REVIEW

**Comment by billmal071** [comment]
Pull to get latest changes, then push again.

**Review by JulianaSau — CHANGES_REQUESTED** [review]
Hi @bimbo-ade, I've reviewed your task and what you're supposed to do is ensure that those icons are of the same size. Currently, they seem to be of different sizes. So instead of making them black, you can keep them colored and ensure they look similar and are of the same size

**Comment by JulianaSau** [comment]
@bimbo-ade ,any update on the requested changes?

**Comment by bimbo-ade** [comment]
> 

i just got access to my pc.. starting work immediately @JulianaSau

**Comment by JulianaSau** [comment]
Okay

**Pull request closed without merging**
