### PR TITLE
[ZUR-171] Fix Bottom Alignment of Message Panel and Page Scroll Issue

### PR DESCRIPTION
**Pull request by adedotxn**
**Ticket Link :** https://linear.app/zurichat2/issue/ZUR-171/chats-channel-should-be-bottom-aligned-and-should-not-scroll-like-it
###  **ISSUE 1 : Fix Bottom Alignment** 
The **first picture shows the initial alignment** while the **second picture shows the fix**
Screenshot (2993)
Screenshot (3000)

###  **ISSUE 2 : Page should not start scrolling to the bottom on page load** (i.e : _page should be at the bottom on page load_  )
**This video demonstrates the fixed issue**

https://user-images.githubusercontent.com/74747245/201498861-173e38f5-b7e5-4196-a4d1-183d2fc1e13f.mp4

### CODE REVIEW

**Comment by JulianaSau** [comment]
Hi @adedotxn. Changes are okay. The problem is you're not working with the updated code.
Pull changes from upstream so that you get the new code and push to your remote repository

**Comment by adedotxn** [comment]
> Hi @adedotxn. Changes are okay. The problem is you're not working with the updated code. Pull changes from upstream so that you get the new code and push to your remote repository

It was up to date at the time I created the pull request but I've pulled the updated changes and pushed them to my remote repository

Screenshot (3003)

**Comment by adedotxn** [comment]
> Hi @adedotxn. Changes are okay. The problem is you're not working with the updated code. Pull changes from upstream so that you get the new code and push to your remote repository

@JulianaSau   It was up to date at the time I created the pull request but I've pulled the updated changes now and pushed them to my remote repository

Screenshot (3003)

**Comment by JulianaSau** [comment]
Okay

**Pull request merged**
