### PR TITLE
Integrate a gif platform (Giphy Platform)

### PR DESCRIPTION
**Pull request by Ojerinde**
https://linear.app/zurichat2/issue/ZUR-182/integrate-a-gif-platform.

On clicking on the gif icon, a modal containing a lists of gifs with infinite scrolling and a search form is displayed.

ScreenShot_20221112201428

ScreenShot_20221112201712

### CODE REVIEW

**Comment by JulianaSau** [comment]
Provide a video instead of screenshots @Ojerinde

**Comment by Ojerinde** [comment]
@JulianaSau 

https://user-images.githubusercontent.com/104495751/201491532-e4e2f241-dab3-413f-a257-bc9d002ec938.MP4

**Review by JulianaSau — APPROVED** [review]

**Comment by JulianaSau** [comment]
Pull changes from the dev branch into your branch to update your pr. After you've done that I can now merge your changes

**Comment by Ojerinde** [comment]
Done with it @JulianaSau

**Comment by JulianaSau** [comment]
Pull again. I merged a couple of prs before this

**Comment by Ojerinde** [comment]
> Pull again. I merged a couple of prs before this

**Comment by Ojerinde** [comment]
Done ma @JulianaSau

**Comment by JulianaSau** [comment]
Pull again. I just merged another pr

**Comment by Ojerinde** [comment]
Okay, done.

**Comment by Ojerinde** [comment]
Thanks.

**Pull request merged**
