### PR TITLE
Search bar component

### PR DESCRIPTION
**Pull request by goforprodev**
slack-username : @prodev

### CODE REVIEW

**Comment by goforprodev** [comment]
searchComponent

**Worked on the search bar component**
.replicated search bar component design

**Comment by markessien** [comment]
No testing link

**Comment by markessien** [comment]
502 bad gateway

**Comment by sammiearchie77** [comment]
your PR failed.... Create a new one

**Comment by AbaniwoM** [comment]
Good afternoon sir. Please I didn't work on this issue. It's not for my
team. My team is Team Einstein and my issue number is #452 Notification
sound settings. Please could you check to confirm sir. Thank you.

**Comment by AbaniwoM** [comment]
Good afternoon sir. Please I didn't work on this issue. It's not for my
team. My team is Team Einstein and my issue number is #452 Notification
sound settings. Please could you check to confirm sir. Thank you.

**Comment by goforprodev** [comment]
Micheal what's going on

**Pull request merged**
