### PR TITLE
ZUR-151 My PR cleans up the legal page and added the loader component

### PR DESCRIPTION
**Pull request by kleenpulse**
I cleaned up the legal (terms) page, which was previously filled with dummy text(lorem ipsum), and added the GeneralLoading component with the text: 404 - (Refactoring in Progress)
slack username: Liquidঐ
linear: liquid

### CODE REVIEW

**Comment by billmal071** [comment]
Provide a way for me to see what you did.

**Comment by kleenpulse** [comment]
> Provide a way for me to see what you did.

the legal page was filled with lorem ipsum dummy text, I clean it up and added the GeneralLoading Component also added the text, as instructed

**Comment by JulianaSau** [comment]
@kleenpulse Provide a video/screenshot of the page you worked on before and after the changes you made

**Comment by kleenpulse** [comment]
terms
before, lorem ipsum
====================
ZUR-151-Liquid

after : Refactoring in progress

**Review by JulianaSau — APPROVED** [review]

**Comment by JulianaSau** [comment]
Pull changes from the dev branch so that i can merge

**Pull request merged**
