### PR TITLE
Reduce the size of the big header area on the marketplace page

### PR DESCRIPTION
**Pull request by Davidlloyd8**

### CODE REVIEW

**Comment by a11rew** [comment]
Check the files your pr changes.

**Comment by Davidlloyd8** [comment]
Rebase ??
How do i rebase

**Comment by a11rew** [comment]
https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch

**Comment by Davidlloyd8** [comment]
Can you recheck

**Comment by Davidlloyd8** [comment]
Have try to rebase it but not going through

any help on that??

**Pull request closed without merging**
