### PR TITLE
Fixed Styling bugs in Pricing page

### PR DESCRIPTION
**Pull request by Joblyn**
- Aligned "Get Started" Buttons on Pricing page for desktop view
- Edited size of "Get Started" Buttons
Issue #1634
##### Before 
Screenshot from 2021-10-10 11-30-52

##### After
Screenshot from 2021-10-11 00-23-49

### CODE REVIEW

**Comment by a11rew** [comment]
@Joblyn This is what it looks like after your changes?

**Comment by Joblyn** [comment]
Yes

**Comment by Joblyn** [comment]
Benefits are not misaligned. 
Buttons are of equal width and height.

**Comment by Joblyn** [comment]
Changes made. Kindly review. @a11rew

**Comment by a11rew** [comment]
Enterprise Grid description references Slack in the description. Please update that.

**Comment by Joblyn** [comment]
Changes made. Kindly merge.

**Pull request merged**
