### PR TITLE
Add New Zuri-bot Keyword

### PR DESCRIPTION
**Pull request by chuksdozie**
User should be able to add a new keyword and zuri-bot response.

Link to Linear Issue
- [x] https://linear.app/zuri/issue/ZC-2859/add-new-zuri-bot-keyword

### CODE REVIEW

**Comment by chuksdozie** [comment]
@a11rew @Boluwatt

**Comment by a11rew** [comment]
> @a11rew @Boluwatt

You've not resolved your reviews.

**Comment by chuksdozie** [comment]
where are the changes resquested

**Comment by a11rew** [comment]
Oh sorry I'd made the review but hadn't submitted

**Comment by chuksdozie** [comment]
@a11rew what would you have me do?

**Pull request closed without merging**
